
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: learner-backend
    environment:
      - DATABASE_URL=sqlite:////app/learner/learner.db
    env_file:
      - .env
    volumes:
      - ./backend/data:/app/data
      - ./backend/app:/app/app
      - ~/.cache/shared/learner:/app/learner
    networks:
      - learner-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: learner-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - learner-network
    restart: unless-stopped

networks:
  learner-network:
    driver: bridge

volumes:
  backend-data:

